Critic_table:
  #Learning rate
  learning_rate: 0.01

  #Discount Factor
  discount_factor: 0.9

  #Eligibility decay
  eli_decay: 0.85

  #Dims (Will be ignored for TableCritic)
  # NOTE: dims[0] MUST equal size**2 if Diamondboard or size(size+1)/2 if Triangle
  dims : !!python/tuple [15,3,1]

Actor:
  #Learning rate
  learning_rate: 0.7

  #Discount Factor
  discount_factor: 0.9

  #Eligibility decay
  eli_decay: 0.85

  #Epsilon
  epsilon: 0.8

  #Epsilon decay
  epsilon_decay: 0.990

Environment:

  #Boardsize
  boardsize: 5

  #Boardtype
  board_type: "Triangle"

  #Open cells
  open_cells: [!!python/tuple [2,1]]

  #Step reward
  step_reward: 1

  #Final reward
  final_reward: 50

  #Loser penalty
  loser_penalty: -100

Training:
  #Number of training episodes
  number_of_episodes: 500
