Critic:
  #Learning rate
  learning_rate: 0.001

  #Discount Factor
  discount_factor: 0.9

  #Eligibility decay
  eli_decay: 0.85

  #Dims (Will be ignored for TableCritic)
  # NOTE: dims[0] MUST equal size**2 if Diamondboard or size(size+1)/2 if Triangle
  dims: !!python/tuple [25, 20, 5, 1]
  #[25,4,3,1]

Actor:
  #Learning rate
  learning_rate: 0.7

  #Discount Factor
  discount_factor: 0.9

  #Eligibility decay
  eli_decay: 0.85

  #Epsilon
  epsilon: 1

  #Final epsilon
  final_epsilon: 0.01

Environment:
  #Boardsize
  boardsize: 5

  #Boardtype
  board_type: "Diamond"

  #Open cells
  open_cells: [!!python/tuple [2, 1]]
  #Works: [2, 1], [0, 0]

  #Step reward
  step_reward: 1

  #Final reward
  final_reward: 50000

  #Loser penalty
  loser_penalty: -20

Training:
  #Number of training episodes
  number_of_episodes: 3000

Critic_type:
  neural: True
